language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.5.1"
  matrix:
   - DJANGO="django==1.8.15"
   - DJANGO="django==1.9.10"
   - DJANGO="django==1.10.2"
   - DJANGO="django==1.10.2" LINT=1
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install flake8
script:
 - ./runtests.sh
