language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
env:
  global:
   - DRF="djangorestframework==3.6.4"
  matrix:
   - DJANGO="django==1.8.18"
   - DJANGO="django==1.10.8"
   - DJANGO="django==1.11.5"
   - DJANGO="django==1.11.5" LINT=1
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install flake8
script:
 - ./runtests.sh
