language: python
sudo: false
python:
 - "3.4"
env:
  global:
   - DRF="https://github.com/tomchristie/django-rest-framework/archive/master.zip"
   - DJANGO="django==1.9.3"
   - WQDB=https://github.com/wq/wq.db/archive/master.zip"
  matrix:
   - LINT=
   - LINT=1
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install $WQDB
 - pip install flake8
script:
 - ./runtests.sh
