language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: [DJANGO=1.8.18, DRF=3.6.4]
    - python: "2.7"
      env: [DJANGO=1.11.12, DRF=3.8.2]
    - python: "3.4"
      env: [DJANGO=1.8.18, DRF=3.6.4]
    - python: "3.4"
      env: [DJANGO=2.0.4, DRF=3.8.2]
    - python: "3.5"
      env: [DJANGO=2.0.4, DRF=3.8.2]
    - python: "3.6"
      env: [DJANGO=1.11.12, DRF=3.8.2]
    - python: "3.6"
      env: [DJANGO=2.0.4, DRF=3.8.2]
    - python: "3.6"
      env: [DJANGO=2.0.4, DRF=3.8.2, LINT=1]
install:
 - pip install django==$DJANGO
 - pip install djangorestframework==$DRF
 - pip install flake8
script:
 - ./runtests.sh
